language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t shani/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true shani/docker-react npm run test